# Generated by Django 3.2.4 on 2021-07-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('nomContacto', models.CharField(max_length=200, verbose_name='Nombre Contacto')),
                ('apeContacto', models.CharField(max_length=200, verbose_name='Apellido Contacto')),
                ('rutContacto', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut Contacto')),
                ('telContacto', models.IntegerField(verbose_name='Telefono Contacto')),
                ('CorreoContacto', models.CharField(max_length=200, verbose_name='Correo Contacto')),
                ('ComenContacto', models.CharField(max_length=255, verbose_name='Comentario Contacto')),
            ],
        ),
    ]
